orig_cwd: "."
# from debug to cluster running: change ddp => true, change logger => true
mode:
  ddp: true # false # true # false 
  nni: false
  accelerate: false # true # false

task:
  type: regression 
  
  regression: 
    default_metric: spearman # spearman


features:
  type: LLM  # CellTree-cnn # breeze # CellTree-rnn # AMPSpace, HC, CellTree-rnn, CellTree-cnn


train:
  random_seed: 0
  num_epoch: 2 #50 # 2 # 50
  batch_size: 4 # 4 # 512 # 512 # 1024 # 8
  num_workers: 1
  learning_rate: 1e-4
  adam_epsilon: 1e-8
  weight_decay: 0.2
  loss: 'mse' # 'huber' # 'mse','huber','tmse'
  lr_scheduler:
    type: cosine # cosine, plateau
    when: batch  # batch, epoch
    cosine:
      T_0: 10
      T_mult: 2
      eta_min: 1e-6
  eval_epoch: 2
  pin_memory: False
  device_ids: [0,1,2,3,4,5,6,7]

model:
  config_dir: "/data/public/models/facebook/esm2_t33_650M_UR50D/" # "/data/public/models/facebook/esm2_t33_650M_UR50D/"# "/data/public/models/gpt2-xl/"# "/data/public/models/facebook/esm2_t12_35M_UR50D" # "/data/public/models/bert-base-uncased/"# "/data/public/models/ProtGPT2/"# "/data/public/models/bert-base-uncased/"# "/data/public/models/ProtGPT2/"# "/data/public/models/facebook/esm2_t12_35M_UR50D/" # esm2_t12_35M_UR50D" # "esm2_t6_8M_UR50D" # "/data/public/models/llama/llama-13b/" # "/data/public/models/facebook/esm2_t48_15B_UR50D/" # "" # "/data/public/models/facebook/esm2_t36_3B_UR50D/" # "roberta-base", "facebook/bart-base","facebook/esm2_t33_650M_UR50D", "facebook/esm1b_t33_650M_UR50S","bert-base-uncased", "xlnet-base-cased", "gpt2"
  regression:
    version: esm2_t33 # esm2_t33 # gpt2-large # bert-base # protgpt2 # CellTree-cnn # breeze # CellTree-rnn # AMPSpace # v1 # AMPSpace, CellTree-cnn, SeqUNet
    check_point: 
      load: false
      path: "/data/home/scv6872/AMPCliff/outputs/2024-03-07/11-10-48/None/model_step_17_spearman_0.626/" 
data:
  max_length: 28
  diff: 5
  regression:

    mode: 'fix' #'fix'
    
    noise_level: 0 # 10 level in total
    
    fix:
      diff5:
        train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/grampa_s_aureus_7_25-tanimoto average-train.csv" 
        valid_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/grampa_s_aureus_7_25-tanimoto average-valid.csv" 
        test_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/grampa_s_aureus_7_25-tanimoto average-test.csv"     
      diff4:
        train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 4/grampa_s_aureus_7_25-tanimoto average-train.csv" 
        valid_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 4/grampa_s_aureus_7_25-tanimoto average-valid.csv" 
        test_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 4/grampa_s_aureus_7_25-tanimoto average-test.csv"
      diff3:
        train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 3/grampa_s_aureus_7_25-tanimoto average-train.csv" 
        valid_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 3/grampa_s_aureus_7_25-tanimoto average-valid.csv" 
        test_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 3/grampa_s_aureus_7_25-tanimoto average-test.csv"
      diff2:
        train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 2/grampa_s_aureus_7_25-tanimoto average-train.csv" 
        valid_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 2/grampa_s_aureus_7_25-tanimoto average-valid.csv" 
        test_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 2/grampa_s_aureus_7_25-tanimoto average-test.csv"
        
logger:
  log: True
  log_dir: "outputs"
  log_per_steps: 10
  final_artifact_path: final

other:
  debug: true # false # false # False
  debug_step: 5
