orig_cwd: "."
# from debug to cluster running: change ddp => true, change logger => true
mode:
  ddp: false # true # false 
  nni: false
  accelerate: false # true # false
  # full: false # training full dataset
  # data: random # random, test_not_in_train, test_in_train
  # debiase: false
  # deepspeed:
  #   config: /data/home/scv6872/Breeze/configs/ds_config.json

# defaults:
#   - regressor: peptimizer
  
task:
  type: regression # regression # rank # regression # regression # regression # pretrain # binary # affinity, multitask, contact_map
  binary: 
    default_metric: accuracy
  # pretrain:  
  #   default_metric: accuracy # loss
  regression: 
    default_metric: spearman # spearman
  rank:
    default_metric: spearman

features:
  type: HC # CellTree-rnn # amino_acid # AMPSpace, HC, CellTree-rnn, CellTree-cnn


train:
  random_seed: 0
  

model:
  dir: /data/home/scv6872/Breeze/models/files/t12
  regression:
    version: HC # CellTree-rnn # AMPSpace # v1 # AMPSpace, CellTree-cnn
    
data:
  max_length: 28
  binary:
    mode: 'fix'
    fix:
      train_file: "/home/bingxing2/home/scx6509/test/Breeze/dataset/all_data_v15u.csv" # AMPBERT.csv" 
      valid_file: "/home/bingxing2/home/scx6509/test/Breeze/dataset/eval_v15u.csv" # AMPBERT.csv"
    
  regression:
    mode: 'fix' # 'fixed_cluster' # 'random' # random' # 'random', 'cluster','fix'
    noise_level: 0 # 10 level in total
    cluster:
      data_file: "/data/home/scv6872/Breeze/downstream/regression/grampa_s_aureus_10-13_smiles_levenshtein_1-6.csv" # AMPBERT.csv" 
      fold_files: "/data/home/scv6872/Breeze/downstream/regression/cluster"
      checkpoints: []
    
    random:
      data_file: "/data/home/scv6872/Breeze/downstream/regression/grampa_s_aureus_7_25_ratio_0.5v0_sampled.csv" # '/data/home/scv6872/Breeze/downstream/regression/grampa_s_aureus_7_25_remove_ac_and_ratio_0.5v0.csv' # "/data/home/scv6872/Breeze/downstream/regression/grampa_e_coli_7_25.csv" # "/data/home/scv6872/Breeze/downstream/regression/grampa_e_coli_7_25.csv" # "/data/home/scv6872/Breeze/downstream/regression/grampa_s_aureus_10-13_smiles_levenshtein_1-5.csv" # AMPBERT.csv" 
      fold: 5
      stratified: True
      fold_files: "/data/home/scv6872/Breeze/downstream/regression/e_coli/stratifiedfolds0"
      checkpoints: ['/data/home/scv6872/Breeze/outputs/2023-12-01/22-28-34/fold 0/model_step_2_recall_3.0',
                    # '/data/home/scv6872/Breeze/outputs/2023-12-01/22-28-34/fold 1/model_step_21_recall_3.0',
                    '/data/home/scv6872/Breeze/outputs/2023-12-01/22-28-34/fold 2/model_step_5_recall_2.0',
                    '/data/home/scv6872/Breeze/outputs/2023-12-01/22-28-34/fold 3/model_step_16_recall_4.0',
                    '/data/home/scv6872/Breeze/outputs/2023-12-01/22-28-34/fold 4/model_step_44_recall_3.0']
    fix:
      all_train_file: "/data/home/scv6872/AMPCliff/data/blosum62 average/diff 4/grampa_s_aureus_7_25-blosum62 average-all-train.csv" 
      train_file: "/data/home/scv6872/AMPCliff/data/blosum62 average/diff 4/grampa_s_aureus_7_25-blosum62 average-train.csv" 
      valid_file: "/data/home/scv6872/AMPCliff/data/blosum62 average/diff 4/grampa_s_aureus_7_25-blosum62 average-valid.csv" 
      test_file: "/data/home/scv6872/AMPCliff/data/blosum62 average/diff 4/grampa_s_aureus_7_25-blosum62 average-test.csv" 
    fixed_cluster:
      data_file: "/data/home/scv6872/Breeze/downstream/regression/grampa_s_aureus_7_25_ratio_0.5v0_mmseqs_cluster_sampled_fold.csv" # "/data/home/scv6872/Breeze/downstream/regression/grampa_s_aureus_7_25_ratio_0.5v0_acpair_0_cluster_sampled_fold.csv" # AMPBERT.csv" 
      fold: 5
      fold_files: "/data/home/scv6872/Breeze/downstream/regression/fixed-folds"
      checkpoints: ['']
  rank:
    mode: 'fixed_cluster' # 'random' # random' # 'random', 'cluster','fix'
    
    random:
      data_file: "/data/home/scv6872/Breeze/downstream/regression/grampa_s_aureus_7_25_ratio_0.5v0_acpair_0_sampled.csv" # AMPBERT.csv" 
      fold: 5
      stratified: False
      fold_files: "/data/home/scv6872/Breeze/downstream/regression/folds-pair"
      checkpoints: ['/data/home/scv6872/Breeze/outputs/2023-12-08/14-40-14/fold 0/model_step_22_spearman_0.753'
                    # '/data/home/scv6872/Breeze/outputs/2023-12-08/14-40-14/fold 1/model_step_10_spearman_0.735',
                    # '/data/home/scv6872/Breeze/outputs/2023-12-08/14-40-14/fold 2/model_step_20_spearman_0.759',
                    # '/data/home/scv6872/Breeze/outputs/2023-12-08/14-40-14/fold 3/model_step_19_spearman_0.782',
                    # '/data/home/scv6872/Breeze/outputs/2023-12-08/14-40-14/fold 4/model_step_10_spearman_0.752']
                    # ['/data/home/scv6872/Breeze/outputs/2023-11-28/14-58-59/fold 0/model_step_4_spearman_0.339',
                    # '/data/home/scv6872/Breeze/outputs/2023-11-28/14-58-59/fold 1/model_step_38_spearman_0.268',
                    # '/data/home/scv6872/Breeze/outputs/2023-11-28/14-58-59/fold 2/model_step_42_spearman_0.726',
                    # '/data/home/scv6872/Breeze/outputs/2023-11-28/14-58-59/fold 3/model_step_1_spearman_0.92',
                    # '/data/home/scv6872/Breeze/outputs/2023-11-28/14-58-59/fold 4/model_step_1_spearman_0.935'
                    ]
    fixed_cluster:
      data_file: "/data/home/scv6872/Breeze/downstream/regression/grampa_s_aureus_7_25_ratio_0.5v0_acpair_mmseqs_cluster_sampled_fold.csv" # "/data/home/scv6872/Breeze/downstream/regression/grampa_s_aureus_7_25_ratio_0.5v0_acpair_0_cluster_sampled_fold.csv" # AMPBERT.csv" 
      fold: 5
      fold_files: "/data/home/scv6872/Breeze/downstream/regression/fixed-folds-pair"
      checkpoints: ['']
    fix:
      train_file: "/data/home/scv6872/Breeze/downstream/regression/train/grampa_s_aureus_10-13u.csv" # grampa_s_aureus_10-13u.csv # AMPBERT.csv" 
      valid_file: "/data/home/scv6872/Breeze/downstream/regression/test/grampa_s_aureus_10-13.csv" # AMPBERT.csv"
    
logger:
  log: True
  log_dir: "outputs"
  log_per_steps: 10
  final_artifact_path: final

other:
  debug: false # false # false # False
  debug_step: 5
