orig_cwd: "."
# from debug to cluster running: change ddp => true, change logger => true
mode:
  ddp: false # true # false 
  nni: false
  accelerate: false # true # false

  
task:
  type: regression # regression # rank # regression # regression # regression # pretrain # binary # affinity,
features:
  type: HC # CellTree-rnn # amino_acid # AMPSpace, HC, CellTree-rnn, CellTree-cnn


train:
  random_seed: 0

data:
  max_length: 28
  diff: 5
  regression:
    mode: 'fix' # 'fixed_cluster' # 'random' # random' # 'random', 'cluster','fix'
    noise_level: 0 # 10 level in total
    condition: 'blosum62 average'#  "blosum62 average" # tanimoto average
    acindex: false
    fix:
      all_train_file: "/data/home/scv6872/AMPCliff/data/blast/{condition}/diff_{diff}/grampa_s_aureus_7_25-all-train.csv"# "/data/home/scv6872/AMPCliff/data/blast/blosum62 average/diff_5/grampa_s_aureus_7_25-all-train.csv"# "/data/home/scv6872/AMPCliff/data/blosum62 average/grampa_s_aureus_7_25-blosum62 average-all-train.csv" 
      train_file: "/data/home/scv6872/AMPCliff/data/blast/{condition}/diff_{diff}/grampa_s_aureus_7_25-train.csv"#"/data/home/scv6872/AMPCliff/data/blast/blosum62 average/diff_5/grampa_s_aureus_7_25-train.csv"  # "/data/home/scv6872/AMPCliff/data/blosum62 average/grampa_s_aureus_7_25-blosum62 average-train.csv" 
      valid_file: "/data/home/scv6872/AMPCliff/data/blast/{condition}/diff_{diff}/grampa_s_aureus_7_25-valid.csv"# "/data/home/scv6872/AMPCliff/data/blast/blosum62 average/diff_5/grampa_s_aureus_7_25-valid.csv"# "/data/home/scv6872/AMPCliff/data/blosum62 average/grampa_s_aureus_7_25-blosum62 average-valid.csv" 
      test_file: "/data/home/scv6872/AMPCliff/data/blast/{condition}/diff_{diff}/grampa_s_aureus_7_25-test.csv"# "/data/home/scv6872/AMPCliff/data/blast/blosum62 average/diff_5/grampa_s_aureus_7_25-test.csv"# "/data/home/scv6872/AMPCliff/data/blosum62 average/grampa_s_aureus_7_25-blosum62 average-test.csv"     
      
logger:
  log: True
  log_dir: "outputs"
  log_per_steps: 10
  final_artifact_path: final

other:
  debug: false # false # false # False
  debug_step: 5
