orig_cwd: "."
# from debug to cluster running: change ddp => true, change logger => true
mode:
  ddp: false # true # false 
  nni: false
  accelerate: false # true # false

  
task:
  type: regression # regression # rank # regression # regression # regression # pretrain # binary # affinity,
features:
  type: HC # CellTree-rnn # amino_acid # AMPSpace, HC, CellTree-rnn, CellTree-cnn


train:
  random_seed: 0

data:
  max_length: 28
  diff: 5
  regression:
    mode: 'fix' # 'fixed_cluster' # 'random' # random' # 'random', 'cluster','fix'
    noise_level: 0 # 10 level in total
    fix:
      diff5:
        all_train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/grampa_s_aureus_7_25-tanimoto average-all-train.csv" 
        train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/grampa_s_aureus_7_25-tanimoto average-train.csv" 
        valid_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/grampa_s_aureus_7_25-tanimoto average-valid.csv" 
        test_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/grampa_s_aureus_7_25-tanimoto average-test.csv"     
      diff4:
        all_train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 4/grampa_s_aureus_7_25-tanimoto average-all-train.csv"
        train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 4/grampa_s_aureus_7_25-tanimoto average-train.csv" 
        valid_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 4/grampa_s_aureus_7_25-tanimoto average-valid.csv" 
        test_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 4/grampa_s_aureus_7_25-tanimoto average-test.csv"
      diff3:
        all_train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 3/grampa_s_aureus_7_25-tanimoto average-all-train.csv"
        train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 3/grampa_s_aureus_7_25-tanimoto average-train.csv" 
        valid_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 3/grampa_s_aureus_7_25-tanimoto average-valid.csv" 
        test_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 3/grampa_s_aureus_7_25-tanimoto average-test.csv"
      diff2:
        all_train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 2/grampa_s_aureus_7_25-tanimoto average-all-train.csv"
        train_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 2/grampa_s_aureus_7_25-tanimoto average-train.csv" 
        valid_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 2/grampa_s_aureus_7_25-tanimoto average-valid.csv" 
        test_file: "/data/home/scv6872/AMPCliff/data/tanimoto average/diff 2/grampa_s_aureus_7_25-tanimoto average-test.csv"
    
logger:
  log: True
  log_dir: "outputs"
  log_per_steps: 10
  final_artifact_path: final

other:
  debug: false # false # false # False
  debug_step: 5
